export const ROLE_HIERARCHY = {
  ADMIN: [
    'GERENTE_GERAL',
    'GERENTE_VENDAS',
    'GERENTE_ESTOQUE',
    'VENDEDOR',
    'ESTOQUISTA',
    'ENTREGADOR',
  ],
  GERENTE_GERAL: [
    'GERENTE_VENDAS',
    'GERENTE_ESTOQUE',
    'VENDEDOR',
    'ESTOQUISTA',
    'ENTREGADOR',
  ],
  GERENTE_VENDAS: ['VENDEDOR'],
  GERENTE_ESTOQUE: ['ESTOQUISTA'],
  VENDEDOR: [],
  ESTOQUISTA: [],
  ENTREGADOR: [],
} as const
